// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Entities
{
    public partial class Base_Auth_User
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string DepCode { get; set; }
        public string EmpId { get; set; }
        public string PasswordHash { get; set; }
        public DateTimeOffset? LastSignInDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTimeOffset? CreatedDate { get; set; }
        public Guid? ModifiedBy { get; set; }
        public DateTimeOffset? ModifiedDate { get; set; }
        public int Cix { get; set; }
    }
}