CREATE TABLE [dbo].[Base_Setting_Code]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [TypeId] UNIQUEIDENTIFIER NOT NULL, 
    [Code] NVARCHAR(50) NOT NULL, 
    [Name] NVARCHAR(200) NOT NULL,
    [Description] NVARCHAR(500) NULL,
    [OptionValue] NVARCHAR(MAX) NULL,
    [Seq] INT NULL,
    [CreatedBy] UNIQUEIDENTIFIER NULL,
	[CreatedDate] DATETIMEOFFSET NULL DEFAULT GETDATE(),
	[ModifiedBy] UNIQUEIDENTIFIER NULL,
	[ModifiedDate] DATETIMEOFFSET NULL
)
